// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package sessionservice

import (
	"context"
	"time"

	"google.golang.org/adk/session"
)

type Service interface {
	Create(context.Context, *CreateRequest) (StoredSession, error)
	Get(context.Context, *GetRequest) (StoredSession, error)
	List(context.Context, *ListRequest) ([]StoredSession, error)
	Delete(context.Context, *DeleteRequest) error
	AppendEvent(context.Context, StoredSession, *session.Event) error
}

func Mem() Service {
	return &inMemoryService{}
}

type StoredSession interface {
	ID() session.ID
	State() session.ReadOnlyState
	Events() session.Events
	Updated() time.Time
}

type CreateRequest struct {
	AppName   string
	UserID    string
	SessionID string // optional: if it's not set it will be autogenerated.
	State     map[string]any
}

type GetRequest struct {
	ID session.ID

	// Optional fields.
	NumRecentEvents int
	After           time.Time
}

type ListRequest struct {
	AppName string
	UserID  string
}

// TODO: potentially consider returning lightweight struct in the List().
// type SessionInfo struct {
// 	ID      session.ID
// 	Updated time.Time
// }

type DeleteRequest struct {
	ID session.ID
}
